name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Maven
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Install with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test